apiVersion: v1
kind: Service
metadata:
  name: investmentology-api
  namespace: investmentology
  labels:
    app: investmentology-api
spec:
  type: ClusterIP
  selector:
    app: investmentology-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
