apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: investmentology-cloudflare
  namespace: investmentology
  labels:
    app.kubernetes.io/name: investmentology
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: haute-banque.kernow.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: investmentology
                port:
                  number: 80
