apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: investmentology-ingress
  namespace: investmentology
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/websocket-services: "investmentology-api"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: invest.kernow.io
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: investmentology-api
                port:
                  number: 8000
          - path: /ws/
            pathType: Prefix
            backend:
              service:
                name: investmentology-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: investmentology-pwa
                port:
                  number: 80
