apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: investmentology

resources:
  - namespace.yaml
  - api-configmap.yaml
  - postgres-secret.yaml
  - api-deployment.yaml
  - api-service.yaml
  - pwa-deployment.yaml
  - pwa-service.yaml
  - ingress.yaml
  - cronjob-screen.yaml
