apiVersion: v1
kind: Service
metadata:
  name: investmentology
  namespace: investmentology
  labels:
    app.kubernetes.io/name: investmentology
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: investmentology
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30580
      protocol: TCP
