apiVersion: v1
kind: Service
metadata:
  name: investmentology
  namespace: investmentology
  labels:
    app.kubernetes.io/name: investmentology
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: investmentology
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
